/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { LocksProtocol, LocksProtocolInterface } from "../LocksProtocol";

const _abi = [
  {
    anonymous: false,
    inputs: [],
    name: "Stopped",
    type: "event",
  },
  {
    inputs: [],
    name: "governor",
    outputs: [
      {
        internalType: "contract IGovernor",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "stopped",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    name: "validUpdate",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class LocksProtocol__factory {
  static readonly abi = _abi;
  static createInterface(): LocksProtocolInterface {
    return new utils.Interface(_abi) as LocksProtocolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LocksProtocol {
    return new Contract(address, _abi, signerOrProvider) as LocksProtocol;
  }
}
