/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface FullMathEchidnaTestInterface extends ethers.utils.Interface {
  functions: {
    "checkMulDiv(uint256,uint256,uint256)": FunctionFragment;
    "checkMulDivRounding(uint256,uint256,uint256)": FunctionFragment;
    "checkMulDivRoundingUp(uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkMulDiv",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkMulDivRounding",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkMulDivRoundingUp",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkMulDiv",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkMulDivRounding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkMulDivRoundingUp",
    data: BytesLike
  ): Result;

  events: {};
}

export class FullMathEchidnaTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: FullMathEchidnaTestInterface;

  functions: {
    checkMulDiv(
      x: BigNumberish,
      y: BigNumberish,
      d: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    checkMulDivRounding(
      x: BigNumberish,
      y: BigNumberish,
      d: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    checkMulDivRoundingUp(
      x: BigNumberish,
      y: BigNumberish,
      d: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  checkMulDiv(
    x: BigNumberish,
    y: BigNumberish,
    d: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  checkMulDivRounding(
    x: BigNumberish,
    y: BigNumberish,
    d: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  checkMulDivRoundingUp(
    x: BigNumberish,
    y: BigNumberish,
    d: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    checkMulDiv(
      x: BigNumberish,
      y: BigNumberish,
      d: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    checkMulDivRounding(
      x: BigNumberish,
      y: BigNumberish,
      d: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    checkMulDivRoundingUp(
      x: BigNumberish,
      y: BigNumberish,
      d: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    checkMulDiv(
      x: BigNumberish,
      y: BigNumberish,
      d: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkMulDivRounding(
      x: BigNumberish,
      y: BigNumberish,
      d: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkMulDivRoundingUp(
      x: BigNumberish,
      y: BigNumberish,
      d: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkMulDiv(
      x: BigNumberish,
      y: BigNumberish,
      d: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkMulDivRounding(
      x: BigNumberish,
      y: BigNumberish,
      d: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkMulDivRoundingUp(
      x: BigNumberish,
      y: BigNumberish,
      d: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
