/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ProtocolDataAggregatorInterface extends ethers.utils.Interface {
  functions: {
    "convertSqrtPriceX96ToTick(uint160)": FunctionFragment;
    "convertTickToSqrtPriceX96(int24)": FunctionFragment;
    "getIncentivizedPools()": FunctionFragment;
    "getLockedNFTIDs(uint32,uint32)": FunctionFragment;
    "getUniswapPositionTickStatuses(uint256[])": FunctionFragment;
    "governor()": FunctionFragment;
    "nftPositionManager()": FunctionFragment;
    "positionsCollateralization(uint64[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "convertSqrtPriceX96ToTick",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertTickToSqrtPriceX96",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIncentivizedPools",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLockedNFTIDs",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUniswapPositionTickStatuses",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "governor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nftPositionManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "positionsCollateralization",
    values: [BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "convertSqrtPriceX96ToTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertTickToSqrtPriceX96",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIncentivizedPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLockedNFTIDs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUniswapPositionTickStatuses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nftPositionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "positionsCollateralization",
    data: BytesLike
  ): Result;

  events: {};
}

export class ProtocolDataAggregator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ProtocolDataAggregatorInterface;

  functions: {
    convertSqrtPriceX96ToTick(
      sqrtPriceX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    convertTickToSqrtPriceX96(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getIncentivizedPools(
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber] & { pool: string; rewardsPortion: BigNumber })[]
      ] & {
        poolConfigs: ([string, BigNumber] & {
          pool: string;
          rewardsPortion: BigNumber;
        })[];
      }
    >;

    getLockedNFTIDs(
      start: BigNumberish,
      end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { nftIDs: BigNumber[] }>;

    getUniswapPositionTickStatuses(
      nftIDs: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, string, number, number, number] & {
          token0: string;
          token1: string;
          fee: number;
          tickLower: number;
          tickUpper: number;
        })[]
      ] & {
        tickStatuses: ([string, string, number, number, number] & {
          token0: string;
          token1: string;
          fee: number;
          tickLower: number;
          tickUpper: number;
        })[];
      }
    >;

    governor(overrides?: CallOverrides): Promise<[string]>;

    nftPositionManager(overrides?: CallOverrides): Promise<[string]>;

    positionsCollateralization(
      positionIDs: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { collateralizations: BigNumber[] }>;
  };

  convertSqrtPriceX96ToTick(
    sqrtPriceX96: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  convertTickToSqrtPriceX96(
    tick: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getIncentivizedPools(
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber] & { pool: string; rewardsPortion: BigNumber })[]
  >;

  getLockedNFTIDs(
    start: BigNumberish,
    end: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getUniswapPositionTickStatuses(
    nftIDs: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    ([string, string, number, number, number] & {
      token0: string;
      token1: string;
      fee: number;
      tickLower: number;
      tickUpper: number;
    })[]
  >;

  governor(overrides?: CallOverrides): Promise<string>;

  nftPositionManager(overrides?: CallOverrides): Promise<string>;

  positionsCollateralization(
    positionIDs: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  callStatic: {
    convertSqrtPriceX96ToTick(
      sqrtPriceX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    convertTickToSqrtPriceX96(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIncentivizedPools(
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber] & { pool: string; rewardsPortion: BigNumber })[]
    >;

    getLockedNFTIDs(
      start: BigNumberish,
      end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getUniswapPositionTickStatuses(
      nftIDs: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      ([string, string, number, number, number] & {
        token0: string;
        token1: string;
        fee: number;
        tickLower: number;
        tickUpper: number;
      })[]
    >;

    governor(overrides?: CallOverrides): Promise<string>;

    nftPositionManager(overrides?: CallOverrides): Promise<string>;

    positionsCollateralization(
      positionIDs: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;
  };

  filters: {};

  estimateGas: {
    convertSqrtPriceX96ToTick(
      sqrtPriceX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertTickToSqrtPriceX96(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIncentivizedPools(overrides?: CallOverrides): Promise<BigNumber>;

    getLockedNFTIDs(
      start: BigNumberish,
      end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUniswapPositionTickStatuses(
      nftIDs: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    governor(overrides?: CallOverrides): Promise<BigNumber>;

    nftPositionManager(overrides?: CallOverrides): Promise<BigNumber>;

    positionsCollateralization(
      positionIDs: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    convertSqrtPriceX96ToTick(
      sqrtPriceX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertTickToSqrtPriceX96(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIncentivizedPools(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLockedNFTIDs(
      start: BigNumberish,
      end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUniswapPositionTickStatuses(
      nftIDs: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    governor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nftPositionManager(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    positionsCollateralization(
      positionIDs: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
